### ISSUE TITLE
hook error: "ValueError: not enough values to unpack (expected 2, got 1)"

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-openstack-service-checks#12]
See https://github.com/juju/charm-helpers/issues/344

unit-openstack-service-checks-0: 18:18:39 DEBUG unit.openstack-service-checks/0.juju-log tracer: hooks phase, 0 handlers queued
unit-openstack-service-checks-0: 18:18:39 DEBUG unit.openstack-service-checks/0.juju-log tracer>
tracer: main dispatch loop, 3 handlers queued
tracer: ++   queue handler reactive/openstack_service_checks.py:186:configure_nrpe_endpoints
tracer: ++   queue handler reactive/openstack_service_checks.py:219:do_reconfigure_nrpe
tracer: ++   queue handler reactive/openstack_service_checks.py:239:parse_hooks
unit-openstack-service-checks-0: 18:18:39 INFO unit.openstack-service-checks/0.juju-log Invoking reactive handler: reactive/openstack_service_checks.py:186:configure_nrpe_endpoints
unit-openstack-service-checks-0: 18:18:39 INFO unit.openstack-service-checks/0.juju-log Setting charm primary status True
unit-openstack-service-checks-0: 18:18:40 ERROR unit.openstack-service-checks/0.juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-openstack-service-checks-0/.venv/lib/python3.6/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-openstack-service-checks-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-openstack-service-checks-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-openstack-service-checks-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-openstack-service-checks-0/charm/reactive/openstack_service_checks.py", line 203, in configure_nrpe_endpoints
    helper.create_endpoint_checks(creds)
  File "lib/lib_openstack_service_checks.py", line 221, in create_endpoint_checks
    host, port = check_url.netloc.split(':')
ValueError: not enough values to unpack (expected 2, got 1)

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2019-07-09T18:53:21Z
 * owner: [phausman](https://launchpad.net/~phausman)
 * assignee: [aluria](https://launchpad.net/~aluria)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1835952)

**Comment by sudeephb** [comment]
(by [phausman](https://launchpad.net/~phausman))
Debug session with pdb uncovers, that check_url.netloc contains an IP address of glance simplestream sync, which does not contain port section. This triggers ValueError, since split() returns only one value.

**Comment by sudeephb** [comment]
(by [aluria](https://launchpad.net/~aluria))
Sample (the netloc value without a colon is the glance-simplestreams-sync endpoint):

juju-log check_url = ParseResult(scheme='http', netloc='10.66.111.239:80', path='/swift/v1', params='', query='', fragment='')
juju-log check_url = ParseResult(scheme='http', netloc='10.66.111.62:5000', path='/v3', params='', query='', fragment='')
juju-log check_url = ParseResult(scheme='http', netloc='10.66.111.104:8041', path='', params='', query='', fragment='')
juju-log check_url = ParseResult(scheme='http', netloc='10.66.111.136:9696', path='', params='', query='', fragment='')
juju-log check_url = ParseResult(scheme='http', netloc='10.66.111.171:8778', path='', params='', query='', fragment='')
juju-log check_url = ParseResult(scheme='http', netloc='10.66.111.62:5000', path='/v3', params='', query='', fragment='')
juju-log check_url = ParseResult(scheme='http', netloc='10.66.111.171:8774', path='/v2.1', params='', query='', fragment='')
juju-log check_url = ParseResult(scheme='http', netloc='10.66.111.157:9001', path='', params='', query='', fragment='')
juju-log check_url = ParseResult(scheme='http', netloc='10.66.111.74:8004', path='/v1/$(tenant_id)s', params='', query='', fragment='')
juju-log check_url = ParseResult(scheme='http', netloc='10.66.111.136:9696', path='', params='', query='', fragment='')
juju-log check_url = ParseResult(scheme='http', netloc='10.66.111.104:8041', path='', params='', query='', fragment='')
juju-log check_url = ParseResult(scheme='http', netloc='10.66.111.74:8000', path='/v1', params='', query='', fragment='')
juju-log check_url = ParseResult(scheme='http', netloc='10.66.111.32', path='', params='', query='', fragment='')

**Comment by sudeephb** [comment]
(by [aluria](https://launchpad.net/~aluria))
This bug is related to keystone's bug 1836018
