### ISSUE TITLE
Hook "identity-credentials-relation-changed" failed

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-openstack-service-checks#123]
The unit openstack-service-checks/0 enters in error state when executing the identity-credentials-relation-changed hook.

The hook is issuing the following traceback:

/usr/lib/python3/dist-packages/keystoneauth1/adapter.py:179: UserWarning: Using keystoneclient sessions has been deprecated. Please update your software to use keystoneauth1.
  warnings.warn('Using keystoneclient sessions has been deprecated. '
Traceback (most recent call last):
  File "./hooks/identity-credentials-relation-changed", line 22, in <module>
    main()
  File "/var/lib/juju/agents/unit-openstack-service-checks-0/.venv/lib/python3.6/site-packages/charms/reactive/__init__.py", line 74, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-openstack-service-checks-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-openstack-service-checks-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-openstack-service-checks-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-openstack-service-checks-0/charm/reactive/openstack_service_checks.py", line 177, in render_config
    helper.render_checks(creds)
  File "lib/lib_openstack_service_checks.py", line 212, in render_checks
    self.create_endpoint_checks(creds)
  File "lib/lib_openstack_service_checks.py", line 272, in create_endpoint_checks
    endpoints = self.keystone_endpoints
  File "lib/lib_openstack_service_checks.py", line 363, in keystone_endpoints
    return self._keystone_client.endpoints.list()
  File "/usr/lib/python3/dist-packages/keystoneclient/v3/endpoints.py", line 125, in list
    **kwargs)
  File "/usr/lib/python3/dist-packages/keystoneclient/base.py", line 75, in func
    return f(*args, **new_kwargs)
  File "/usr/lib/python3/dist-packages/keystoneclient/base.py", line 397, in list
    self.collection_key)
  File "/usr/lib/python3/dist-packages/keystoneclient/base.py", line 125, in _list
    resp, body = self.client.get(url, **kwargs)
  File "/usr/lib/python3/dist-packages/keystoneauth1/adapter.py", line 304, in get
    return self.request(url, 'GET', **kwargs)
  File "/usr/lib/python3/dist-packages/keystoneauth1/adapter.py", line 463, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/keystoneauth1/adapter.py", line 189, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/lib/python3/dist-packages/keystoneclient/session.py", line 443, in request
    raise exceptions.from_response(resp, method, url)
keystoneauth1.exceptions.http.ServiceUnavailable: Service Unavailable (HTTP 503)

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2019-11-25T11:12:50Z
 * owner: [msmarcal](https://launchpad.net/~msmarcal)
 * assignee: [None](https://launchpad.net/~None)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1853827)

**Comment by sudeephb** [comment]
(by [msmarcal](https://launchpad.net/~msmarcal))
Subscribed Field High

**Comment by sudeephb** [comment]
(by [afreiberger](https://launchpad.net/~afreiberger))
This appears to be an error on keystone.  50X errors are typically either wsgi errors or haproxy errors.  check the keystone unit logs for issues in /var/log/haproxy.log, /var/log/apache2, and /var/log/keystone finding "ERROR" or "Traceback" or "503" to see why keystone is denying the ability to run an "openstack endpoint list".

**Comment by sudeephb** [comment]
(by [msmarcal](https://launchpad.net/~msmarcal))
While debugging this issue, I discovered that the no_proxy environment variable didn't contain the keystone VIP. After including it on the variable, the error was fixed.
