### ISSUE TITLE
Install on Trusty fails with missing packages

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-openstack-service-checks#18]
Install of release 20.02 on Trusty fails with missing packages:

2020-05-11 04:07:06 DEBUG install E: Unable to locate package python3-keystoneclient
2020-05-11 04:07:06 DEBUG install E: Unable to locate package python3-openstackclient
2020-05-11 04:07:06 DEBUG install Traceback (most recent call last):
2020-05-11 04:07:06 DEBUG install   File "/var/lib/juju/agents/unit-o-s-c-trusty-0/charm/hooks/install", line 8, in <module>
2020-05-11 04:07:06 DEBUG install     basic.bootstrap_charm_deps()
2020-05-11 04:07:06 DEBUG install   File "lib/charms/layer/basic.py", line 85, in bootstrap_charm_deps
2020-05-11 04:07:06 DEBUG install     apt_install(cfg.get('packages', []))
2020-05-11 04:07:06 DEBUG install   File "lib/charms/layer/basic.py", line 239, in apt_install
2020-05-11 04:07:06 DEBUG install     check_call(cmd + packages, env=env)
2020-05-11 04:07:06 DEBUG install   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
2020-05-11 04:07:06 DEBUG install     raise CalledProcessError(retcode, cmd)
2020-05-11 04:07:06 DEBUG install subprocess.CalledProcessError: Command '['apt-get', '--option=Dpkg::Options::=--force-confold', '--assume-yes', 'install', 'nagios-nrpe-server', 'python3-keystoneclient', 'python3-openstackclient', 'python-openstackclient']' returned non-zero exit status 100

We need to decide whether to simply remove Trusty support, or replace these packages with something else.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2020-05-11T04:12:23Z
 * owner: [xavpaice](https://launchpad.net/~xavpaice)
 * assignee: [guoqiao](https://launchpad.net/~guoqiao)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1877923)

**Comment by sudeephb** [comment]
(by [aluria](https://launchpad.net/~aluria))
Besides the APT packages issue, the charm uses layer-snap which would return an error if the unit runs trusty on a container.

**Comment by sudeephb** [comment]
(by [addyess](https://launchpad.net/~addyess))
This commit removed trusty support from this charm if running in a container:
https://git.launchpad.net/charm-openstack-service-checks/commit/?id=533a90c9d6b59ee4f00694cd398c43ac67ef774f

Either we should remove trusty support for the charm (unless it's supported only on trusty metal) or we should update the charm so that trusty can continue to get support.

Looks like the snap layer gets used to install `fcbtest`.

this app is only installable via snap, so it looks like the only recourse is to remove trusty support from this charm.

**Comment by sudeephb** [comment]
(by [guoqiao](https://launchpad.net/~guoqiao))
MP created to remove `trusty` from series in metadata.
