### ISSUE TITLE
StopIteration causes check_nova_services to finish abruptly

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-openstack-service-checks#29]
root@juju-3d3206-0-lxd-5:~# sudo -u nagios /usr/local/lib/nagios/plugins/check_nova_services.py
<function check_nova_services at 0x7f2c9a791848> raised unknown exception '<type 'exceptions.StopIteration'>'
============================================================
Traceback (most recent call last):
  File "/usr/local/lib/nagios/plugins/nagios_plugin.py", line 32, in try_check
    function(*args, **kwargs)
  File "/usr/local/lib/nagios/plugins/check_nova_services.py", line 66, in check_nova_services
    services_compute))
  File "/usr/local/lib/nagios/plugins/check_nova_services.py", line 21, in check_hosts_up
    host_svc = (svc for svc in services_compute if svc['host'] ==
StopIteration
============================================================

Expectation:
Iteration should be caught and issue a "continue" statement.
https://git.launchpad.net/charm-openstack-service-checks/tree/files/plugins/check_nova_services.py#n21

try:
  ...
except StopIteration as e:
  continue

Alternatively, and since a single item is expected, a list could be created (no expectation of mem exhaustion for lazy load).

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2018-11-08T13:38:39Z
 * owner: [aluria](https://launchpad.net/~aluria)
 * assignee: [None](https://launchpad.net/~None)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1802303)

**Comment by sudeephb** [comment]
(by [zzehring](https://launchpad.net/~zzehring))
Encountered this error as well. For my case, if no services (svc) is returned by list comprehension, the error is thrown. This is occurring when there's a host in a host aggregate but no corresponding OS service running on it.
