### ISSUE TITLE
check_octavia_amphorae fails with "NRPE: Unable to read output" message

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-openstack-service-checks#67]
This commit [1] removes amphora check. But the check_octavia_amphorae.cfg is still present on openstack-service-checks unit:

```
$ ls -l /etc/nagios/nrpe.d | grep amphora
-rw-r--r-- 1 root root 256 Oct 24 14:40 check_octavia_amphorae.cfg
```

Running the check from check_octavia_amphorae.cfg file results in "KeyError: 'amphorae'":

```
root@juju-5ebd1b-3-lxd-19:/etc/nagios/nrpe.d# /usr/local/lib/nagios/plugins/check_octavia.py --check amphorae
Traceback (most recent call last):
  File "/usr/local/lib/nagios/plugins/check_octavia.py", line 308, in <module>
    main()
  File "/usr/local/lib/nagios/plugins/check_octavia.py", line 302, in main
    status, message = process_checks(args)
  File "/usr/local/lib/nagios/plugins/check_octavia.py", line 243, in process_checks
    return nagios_exit(args, checks[args.check](connection))
KeyError: 'amphorae'
```

1. https://git.launchpad.net/charm-openstack-service-checks/commit/?id=3c05ef0f762a1bd90628a4ed2f897d0b455d8969

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2022-10-31T08:47:41Z
 * owner: [phausman](https://launchpad.net/~phausman)
 * assignee: [mertkirpici](https://launchpad.net/~mertkirpici)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1995243)

**Comment by sudeephb** [comment]
(by [mertkirpici](https://launchpad.net/~mertkirpici))
The charm that contains a patch for this bug is released to the edge channel. Could you confirm that this issue is solved?

**Comment by sudeephb** [comment]
(by [vern](https://launchpad.net/~vern))
I refreshed to the latest/edge channel:

  juju refresh openstack-service-checks --channel latest/edge

After the charm finished the upgrade, the check_octavia_amphorae.cfg in /etc/nagios/nrpe.d still exists. I don't see the amphorae check mentioned in lib/lib_openstack_service_checks.py any more so I should be able to safely remove /etc/nagios/nrpe.d/check_octavia_amphorae.cfg.

Additionally, now I have a ton of cert errors that weren't there before, such as:

  SSL_CERT CRITICAL nova.os.internal: Cannot find Signed Certificate Timestamps (SCT)

Refreshing back to latest/stable makes the SSL_CERT errors go away.

**Comment by sudeephb** [comment]
(by [phausman](https://launchpad.net/~phausman))
Hi Mert, thanks for working on a patch! I don't have the access to the environment anymore. But let me see if anyone in my team can test it.

**Comment by sudeephb** [comment]
(by [mertkirpici](https://launchpad.net/~mertkirpici))
Thanks Vern and Przemyslaw for the quick response!

> After the charm finished the upgrade, the check_octavia_amphorae.cfg in /etc/nagios/nrpe.d still exists. I don't see the amphorae check mentioned in lib/lib_openstack_service_checks.py any more so I should be able to safely remove /etc/nagios/nrpe.d/check_octavia_amphorae.cfg.

Hmm I think I know the reason behind this. So I removed all reference artifacts to "amphorae" from the previous work, that includes the cleanup routine.. This will work fine for clean installs, however for the upgrade scenario, if we don't want to delete this file manually all the time, I will re-add the "amphora" to cleanup again. tldr: its safe to remove but i should've thought more carefully about this.

> Additionally, now I have a ton of cert errors that weren't there before, such as:

  SSL_CERT CRITICAL nova.os.internal: Cannot find Signed Certificate Timestamps (SCT)

I think these are originating from another issue, for which a patch was merged recently. Please feel free to file a bug with your findings. There was a new check introduced, I am guessing it needs some tuning.
https://bugs.launchpad.net/charm-openstack-service-checks/+bug/1892513
